### ISSUE TITLE
Add amazon ecs api

### ISSUE THREAD

**Issue by konifar** [konifar/annict-android#64]
For images
http://docs.aws.amazon.com/AWSECommerceService/latest/GSG/ImplementinganA2SRequest.html

**Comment by hotchemi** [comment]
Seems nice 👀

**Comment by konifar** [comment]
```
wsimport -s app/src/main/java  -p com.ECS.client.jax http://webservices.amazon.com/AWSECommerceService/AWSECommerceService.wsdl
```

**Comment by konifar** [comment]
http://docs.aws.amazon.com/ja_jp/AWSECommerceService/latest/DG/AuthJavaSampleSig2.html

**Comment by konifar** [comment]
http://webservices.amazon.co.jp/scratchpad/index.html

**Comment by konifar** [comment]
I gave up 😢 
This api has severely usage restrictions. So I will create image server (maybe on heroku), and get image from it.

Anyway the most important thing is to finish to develop this app 😉
