### ISSUE TITLE
Investigate to get twitter profile image

### ISSUE THREAD

**Issue by konifar** [konifar/annict-android#67]
This is revenge of https://github.com/konifar/annict-android/issues/64 🔥 

Annict API does not give image url.
But I can get twitter official account of each anime via API.
So I might be able to use the twitter profile image.
I'll investigate this way.

**Comment by konifar** [comment]
I tried to get twitter profile icon.

<img width="396" alt="screenshot_2016-07-29-21-02-23_jpg__1080x1920_" src="https://cloud.githubusercontent.com/assets/1269214/17247712/27e34916-55d0-11e6-81a2-6408d2290b4c.png">

**Comment by hotchemi** [comment]
Here you go!!!
